
spring:
  application:
    name: api-gateway
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password:     # 密码（默认为空）
    timeout: 60000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    config:
      discovery:
        enabled: true
    nacos:
      discovery:
        server-addr: 139.196.96.251:8848
    # sring cloud路由配置
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service-id
        uri: lb://user-service
        predicates:
        - Path= /user/**
        filters:
        # 限流配置
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@userServiceKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
        # 降级配置
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: 'forward:/fallback'

server:
  port: 1112

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
            strategy: THREAD

ribbon:
  ConnectionTimeout: 10000
  MaxConnectionsPerHost: 10
  MaxAutoRetries: 5
  MaxTotalHttpConnections: 20
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 10000

logging:
  file: ~/logs/api-gateway.log
  level:
    com:
      my: DEBUG
    org:
      springframework:
        web: INFO
